### ISSUE TITLE
Support for OCPP chargers

### ISSUE THREAD

**Issue by lbbrhzn** [tmjo/charger-card#10]
There is now a custom integration for chargers that support the Open Charge Point Protocol. 

See [ocpp](https://github.com/lbbrhzn/ocpp)

I think this is the closest we can get to a universal interface towards the chargers. 

What would be needed to get ocpp working with the charger card?

**Comment by tmjo** [comment]
That sounds cool, I'll take a look at it (won't happen too soon though). I'll try to verify if Easee chargers can benefit from the ocpp too, I remember it was discussed some time ago, but not sure if it is fully supported by Easee.

**Comment by nagydavid** [comment]
Hi @tmjo , @lbbrhzn 

Is there any update on the tuning the card towards OCPP chargers as well. If needed I can help out :)

**Comment by tmjo** [comment]
Hi @nagydavid, I didn't have time to look at it yet. There was done some work to make the card generic though, but it has not been completed yet (see #12). If you would like to test it out there are two branches there which you could test and propose changes to.

**Comment by tmjo** [comment]
I did some work on making the card customizable, please see #19 

It would be great if you could test my proposal and see if it fulfills your requests. For sure there are some bugs, kindly let me know or contribute if you feel for it.

**Comment by dreimer1986** [comment]
I am tinkering with that intention in my mind right now. I am progressing quite well by now, but one thing I do not get working at all. That caused a lil break trying to fx that first. First what I have:

```
    default:
      - text: Max Current
        icon: mdi:current-ac
        service: number.set_value
        service_data:
          entity_id: number.evbox_maximum_current
          value: '#SERVICEVAL#'
```

One of my badly failed experiments:

```
    Available:
      - text: Max Current
        icon: mdi:current-ac
        service: number.set_value
        service_data:
          entity_id: number.evbox_maximum_current
          value: '{{ states("#SERVICEVAL#")|float }}'
```

The OCPP addin gives back the maximum current as number entity and lets it configure by the used service. I do that in a few templates/automations already and it works. You MUST use float numbers though. And here is the problem. Whatever I try, the service call fails with the error that value @ data['value'] is no float. Any idea?
