### ISSUE TITLE
customize the stats

### ISSUE THREAD

**Issue by andybali** [tmjo/charger-card#12]
Can you please add an example to customize the stats....I don´t get it work.

**Comment by tmjo** [comment]
Good point, I'll do that as soon as I find the time. Meanwhile, see i the guide at [vacuum card](https://github.com/denysdovhan/vacuum-card) helps you out (this card is forked from vacuum-card).

**Comment by purcell-lab** [comment]
This is what I have working with the Tesla integration.

```
type: custom:charger-card
entity: sensor.duka_charging_rate_sensor
chargerImage: Anthracite
compact_view: false
show_stats: o
stats:
  default:
    - entity_id: binary_sensor.duka_charger_sensor
      attribute: charging_state
      subtitle: State
    - entity_id: sensor.ev_power
      subtitle: Power
      unit: W
    - entity_id: sensor.duka_charging_rate_sensor
      attribute: charge_energy_added
      subtitle: Energy Added
      unit: kWh
    - entity_id: sensor.duka_charging_rate_sensor
      attribute: charger_actual_current
      subtitle: Actual Current
      unit: A
    - entity_id: sensor.duka_charging_rate_sensor
      attribute: charge_current_request
      subtitle: Requested Current
      unit: A
```
![image](https://user-images.githubusercontent.com/79175134/142701901-8b5d093d-567a-4401-824c-a13e2318f69f.png)

Some further discussion https://github.com/alandtse/tesla/issues/93

**Comment by tmjo** [comment]
Hi @purcell-lab; the card doesn't by default by default support anythign else but the Easee charger integration. I'll be working on implementing other chargers, but probably not car integrations, so I don't really understand your question? Please elaborate.

**Comment by purcell-lab** [comment]
> Hi @purcell-lab; the card doesn't by default by default support anythign else but the Easee charger integration. I'll be working on implementing other chargers, but probably not car integrations, so I don't really understand your question? Please elaborate.

The Tesla integration had a lot of the attributes of a smart charger which are actual features from the car.

Thus using your charger-card it should be possible via the Tesla integration to start and stop charging, set various charging currents and set solar tracking for charging.

The example configuration above displays some Tesla statistics via your charger card; charging status, power, energy and current requested.

I have HA scripts that set charging to 8, 16, 32 Amps or solar tracking. Using your card I should be able to assign action buttons to call these scripts.

We just need to understand the structure your card configuration requires as per issue #6 or use a template to set up an entity with the Tesla attributes but in the easee structure for consumption by this card.

**Comment by alandtse** [comment]
> Hi @purcell-lab; the card doesn't by default by default support anythign else but the Easee charger integration. I'll be working on implementing other chargers, but probably not car integrations, so I don't really understand your question? Please elaborate.

If you're open to suggestions, I might suggest that you generalize the interface a bit so that you don't have to write it for each charger but you can let the community help you. Many of your choices work for other chargers as long as we can have a mapping from your term. 

I actually have a build of your card which allows me to override some of your built in [constants ](https://github.com/tmjo/charger-card/blob/master/src/const.js#L36-L60) with my own strings. It was a PoC but I can probably clean it up and submit it as a PR this weekend.  I believe you have some hard coded items in other parts of the card that can't be overwritten by that method. But after you see my edits you may think of an easy way to generalize it.

**Comment by tmjo** [comment]
Sounds good, always open for suggestions. I made the card specifically for Easee, but I was hoping to find time to generalize it and make it more flexible. This time never appeared, but feel free to make a PR. There was some proposals in a different issue as well, for instance making an template sensor.

**Comment by purcell-lab** [comment]
> I actually have a build of your card which allows me to override some of your built in [constants ](https://github.com/tmjo/charger-card/blob/master/src/const.js#L36-L60) with my own strings. It was a PoC but I can probably clean it up and submit it as a PR this weekend. I believe you have some hard coded items in other parts of the card that can't be overwritten by that method. But after you see my edits you may think of an easy way to generalize it.

@alandtse, I would be interested in this.  I couldn't see a fork on github so I'll await your PR.

**Comment by alandtse** [comment]
> > I actually have a build of your card which allows me to override some of your built in [constants ](https://github.com/tmjo/charger-card/blob/master/src/const.js#L36-L60) with my own strings. It was a PoC but I can probably clean it up and submit it as a PR this weekend. I believe you have some hard coded items in other parts of the card that can't be overwritten by that method. But after you see my edits you may think of an easy way to generalize it.
> 
> @alandtse, I would be interested in this. I couldn't see a fork on github so I'll await your PR.

It's just a work in progress. https://github.com/alandtse/charger-card/tree/override. You have to know the constants in the code, but you override with a root yaml block. Please note, you need the subblock `entity_id` to do an entity override. `attribute` will let you specify an attribute. 

Icons also need to be overridden too.

```yaml
override:
  CURRENTLIMITS:
    - 8
    - 10
    - 16
    - 20
    - 25
    - 32
  CHARGERDOMAIN: tesla
  STANDBY_1: Disconnected
  PAUSED_2: awaiting_start
  CHARGING_3: 'On'
  READY_4: Complete
  ERROR_5: error
  CONNECTED_6: ready_to_charge
  cableLocked:
    entity_id: lock.everest_charger_door_lock
  cableLockedPermanently: switch.cable_locked_permanently
  basicSchedule: true
  circuitCurrent: sensor.circuit_current
  costPerKwh: sensor.cost_per_kwh
  dynamicChargerCurrent: sensor.dynamic_charger_limit
  dynamicCircuitCurrent: sensor.dynamic_circuit_limit
  enableIdleCurrent: switch.enable_idle_current
  inCurrent:
    entity_id: sensor.eva_charging_rate_sensor
    attribute: charger_actual_current
  isEnabled: switch.everest_charger_switch
  maxChargerCurrent:
    entity_id: sensor.eva_charging_rate_sensor
    attribute: charge_current_request
  maxCircuitCurrent: 32
  offlineCircuitCurrent: 32
  isOnline:
    entity_id: binary_sensor.everest_online_sensor
  outputCurrent: sensor.output_limit
  reasonForNoCurrent: sensor.reason_for_no_current
  sessionEnergy:
    entity_id: sensor.eva_charging_rate_sensor
    attribute: charge_energy_added
  energyPerHour:
    entity_id: sensor.everest_charging_rate_sensor
  energyLifetime: sensor.lifetime_energy
  smartCharging:
    entity_id: switch.everest_maxrange_switch
  totalPower:
    entity_id: sensor.everest_charging_rate_sensor
    attribute: charger_power
  updateAvailable: binary_sensor.everest_update_available_sensor
  voltage:
    entity_id: sensor.everest_charging_rate_sensor
    attribute: charger_voltage
  chargerMaxCurrent: set_charger_max_limit
  chargerDynCurrent: set_charger_dynamic_limit
  circuitMaxCurrent: set_charger_circuit_max_limit
  circuitDynCurrent: set_charger_circuit_dynamic_limit
  circuitOfflineCurrent: set_charger_circuit_offline_limit
```
