### ISSUE TITLE
OpenEVSE defaults not working

### ISSUE THREAD

**Issue by firstof9** [tmjo/charger-card#22]
When using `brand` set to `openevse` the card doesn't display any data except the charger status.
Card config:

```yaml
type: custom:charger-card
entity: sensor.openevse_charging_status
brand: openevse
```
![image](https://user-images.githubusercontent.com/1105672/158039132-a7090482-bee9-43b3-a938-d7fcb28125f4.png)

![image](https://user-images.githubusercontent.com/1105672/158039146-d6f3b5a2-c897-43c1-b128-c51a770ac3d0.png)

**Comment by tmjo** [comment]
Hi, it was added as a test and the card is still a release candidate. I depend on someone with EVSE charger to debug and propose template values or I'll have to remove it (bevause I have no clue how it looks).

The card is now fully customizable (even if you have selected a template, it can be modified). So it should be easy to fool around with different settings without knowing code.

**Comment by tmjo** [comment]
Perhaps @jcsogo would like to chime in too, he did some early testing (see #19) and requested the EVSE some time back.

**Comment by jcsogo** [comment]
I haven't migrated yet to the new rewritten card, but what I have quickly looked in the code makes sense. I am using @firstof9  integration, so it should work. But please make sure that you have the default "sensor.openevse_charging_status" as you're defining in the config, as the code will rip the _charging_status part to get the 'openevse' string. If you've named it differently, then you have to pass that sensor to the config.

**Comment by tmjo** [comment]
That's right, the card is using the main sensor to figure out (best guess) the rest of the sensors. But if someone has completely renamed it, the card should work anyway, but will rely on manual configuration of course.

**Comment by firstof9** [comment]
So I came up with something like this:

```yaml
type: custom:charger-card
entity: sensor.openevse_charging_status
brand: openevse
details:
  status:
    entity_id: sensor.openevse_charging_status
  substatus:
    entity_id: sensor.openevse_station_status
  currentlimits:
    - 0
    - 10
    - 12
    - 25
    - 30
    - 32
    - 48
  statetext:
    disconnected: not connected
    awaiting_start: sleeping
    completed: connected
    charging: charging
  collapsiblebuttons:
    group1:
      text: click_for_group1
      icon: mdi:speedometer
    group2:
      text: click_for_group2
      icon: mdi:information
    group3:
      text: click_for_group3
      icon: mdi:cog
  info_left:
    - entity_id: sensor.openevse_wifi_signal_strength
      text: online
  info_right:
    - entity_id: sensor.openevse_charging_voltage
      text: voltage
      unit_show: true
    - entity_id: sensor.openevse_charging_current
      text: Charging Current
      unit_show: true
    - entity_id: sensor.openevse_current_power_usage
      text: power
      unit_show: true
  group1:
    - entity_id: sensor.openevse_max_amps
      text: max_charger_limit
  group2:
    - entity_id: sensor.openevse_wifi_fimrware_version
      text: firmware_version
  group3:
    - entity_id: switch.openevse_manual_override
      text: Manual Override
  stats:
    default:
      - entity_id: sensor.openevse_usage_this_session
        text: session_energy
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: lifetime_energy
        unit_show: true
    disconnected:
      - entity_id: sensor.openevse_usage_this_session
        text: session_energy
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: lifetime_energy
        unit_show: true
    awaiting_start:
      - entity_id: sensor.openevse_usage_this_session
        text: session_energy
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: lifetime_energy
        unit_show: true
    charging:
      - entity_id: sensor.openevse_current_power_usage
        text: power
        unit_show: true
      - entity_id: sensor.openevse_charging_current
        text: Charging Current
        unit_show: true
      - entity_id: select.openevse_max_current
        text: output_limit
        unit_show: true
    completed:
      - entity_id: sensor.openevse_usage_this_session
        text: session_energy
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: lifetime_energy
        unit_show: true
    error:
      - entity_id: sensor.openevse_usage_this_session
        text: session_energy
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: lifetime_energy
        unit_show: true
    ready_to_charge:
      - entity_id: sensor.openevse_usage_this_session
        text: session_energy
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: lifetime_energy
        unit_show: true
  toolbar_left:
    default:
      - {}
    disconnected:
      - {}
    awaiting_start:
      - service: switch.turn_off
        service_data:
          target:
            entity_id: switch.openevse_manual_override
        text: stop
        icon: hass:stop
      - service: switch.turn_on
        service_data:
          target:
            entity_id: switch.openevse_manual_override
        text: start
        icon: hass:play
    charging:
      - service: switch.turn_off
        service_data:
          target:
            entity_id: switch.openevse_manual_override
        text: stop
        icon: hass:stop
    completed:
      - {}
    error:
      - {}
    ready_to_charge:
      - {}
```

Here's the output:

![image](https://user-images.githubusercontent.com/1105672/158455799-995b5dd9-8810-4621-8ac1-992762f7ef51.png)

**Comment by tmjo** [comment]
Starting to look good! I am aware of the glitch you see in current selection dropdown, there is a problem in my css that I didn't manage to fix yet. See #21 as well.

PS! You would probably want to add a service to the current selection too so that you can actually change it?

**Comment by firstof9** [comment]
I've made a few tweaks that may work as defaults:

```yaml
type: custom:charger-card
entity: sensor.openevse_charging_status
brand: openevse
customCardTheme: theme_custom
details:
  status:
    entity_id: sensor.openevse_charging_status
  substatus:
    entity_id: sensor.openevse_station_status
  currentlimits:
    - 6
    - 10
    - 12
    - 25
    - 30
    - 32
    - 48
  statetext:
    awaiting_start: sleeping
    completed: connected
    charging: charging
  collapsiblebuttons:
    group1:
      text: Set Limits
      icon: mdi:speedometer
    group2:
      text: Firmware
      icon: mdi:information
    group3:
      text: Configuration
      icon: mdi:cog
  info_left:
    - entity_id: sensor.openevse_wifi_signal_strength
      text: online
  info_right:
    - entity_id: sensor.openevse_charging_voltage
      text: Voltage
      unit_show: true
    - entity_id: sensor.openevse_charging_current
      text: Charging Current
      unit_show: true
    - entity_id: sensor.openevse_current_power_usage
      text: Power
      unit_show: true
  group1:
    - entity_id: select.openevse_max_current
      text: Max Amps
      icon: mdi:sine-wave
      service: select.select_option
      service_data:
        option: '#SERVICEVAL#'
  group2:
    - entity_id: sensor.openevse_wifi_fimrware_version
      text: Firmware Version
    - entity_id: sensor.openevse_controller_firmware
      text: Controller Firmware
  group3:
    - entity_id: select.openevse_service_level
      icon: mdi:leaf
      text: Service Level
  stats:
    default:
      - entity_id: sensor.openevse_ambient_temperature
        text: Ambient Temp
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: Lifetime Energy
        unit_show: true
      - entity_id: sensor.openevse_charge_time_elapsed
        text: Charge Time
        unit_show: true
    awaiting_start:
      - entity_id: select.openevse_max_current
        text: Current Limit
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: Lifetime Energy
        unit_show: true
      - entity_id: sensor.openevse_ambient_temperature
        text: Ambient Temp
        unit_show: true
    charging:
      - entity_id: select.openevse_max_current
        text: Current Limit
        unit_show: true
      - entity_id: sensor.openevse_esp32_temperature
        text: Station Temp
        unit_show: true
    completed:
      - entity_id: sensor.openevse_usage_this_session
        text: Session Energy
        unit_show: true
      - entity_id: sensor.openevse_total_usage
        text: Lifetime Energy
        unit_show: true
      - entity_id: sensor.openevse_charge_time_elapsed
        text: Charge Time
        unit_show: true
    error:
      - entity_id: sensor.openevse_esp32_temperature
        text: Station Temp
        unit_show: true
      - entity_id: sensor.openevse_ambient_temperature
        text: Ambient Temp
        unit_show: true
      - entity_id: select.openevse_max_current
        text: Current Limit
        unit_show: true
  toolbar_left:
    awaiting_start:
      - service: switch.turn_off
        service_data:
          target:
            entity_id: switch.openevse_manual_override
        text: stop
        icon: hass:stop
      - service: switch.turn_on
        service_data:
          target:
            entity_id: switch.openevse_manual_override
        text: start
        icon: hass:play
    charging:
      - service: switch.turn_off
        service_data:
          target:
            entity_id: switch.openevse_manual_override
        text: stop
        icon: hass:stop
```

![image](https://user-images.githubusercontent.com/1105672/159047763-add1b20a-0ead-4657-bc82-b89d120c08de.png)
