### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by danielbrunt57** [tmjo/charger-card#32]
I had the stable release installed for a long time but never could make it work.
I just installed v0.1.1 pre-release and can't get it to work either.  I've scrolled through all 896 of my sensors and managed to find Wallbox but can't configure the card past there using the visual editor...
![image](https://user-images.githubusercontent.com/49846893/199863135-3a39960f-c44a-4f1a-8f90-e87d0a6ffc54.png)
![image](https://user-images.githubusercontent.com/49846893/199863200-5e3957a7-0dab-41da-a4cc-329a12b80bf6.png)

Using code editor, I have this:
![image](https://user-images.githubusercontent.com/49846893/199868582-6d51df91-6e0a-44e4-8bb2-418775679fbf.png)
![image](https://user-images.githubusercontent.com/49846893/199868955-1c69d450-d171-4ca4-a948-d85c0c0e193f.png)

**Comment by tmjo** [comment]
Hi,

I am aware of some troubles in the UI-configurator after they changed something in HA which I haven't figured out how to fix yet. The best solution for time being (and only solution to use the advance features anyway) is to use manual yaml configuration.

It shouldn't be to hard if you follow the example in the readme, but start simple and then add on more and more features. It would be easier to help you if you post your yaml code as code-snippet and not images (i.e. copy exact and full yaml-code into text and use the <> symbol in gituhub to surround it, then it appears nicely and formatted which is important for yaml).

I see you got some "real" sensors and some that are obviously not exisiting since they are copy from the example, it could be that the card breaks due to this. Try removing some parts of it and add more as you go (start for instance by removing from `group1:` and below). A more advanced method is to open Developer Tools (Ctrl+Shift+I in Chrome) and see what the error message is.

**Comment by danielbrunt57** [comment]
Thanks!  Upon returning to the card and charging was active, items populated.
Here is where I'm at with my yaml...
```
type: custom:charger-card
brand: other
entity: sensor.wallbox_32a_charger
customCardTheme: theme_custom
chargerImage: White
show_leds: true
show_collapsibles: false
details:
  name:
    entity_id: sensor.wallbox_32a_charger
    attribute: name
  location:
    entity_id: sensor.wallbox_32a_charger
    attribute: site_name
  status:
    entity_id: sensor.wallbox_32a_charger
  statetext:
    on: 'Charging'
    off: 'Completed'
  info_left:
    - entity_id: sensor.circuit_11_power
      text: power
      unit_show: true
  info_right:
    - entity_id: sensor.household_voltage
      text: voltage
      unit_show: true
  stats:
    default:
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: sensor.32a_car_charging_session_step_1
          - entity_id: sensor.32a_car_charging_session_step_2
        text: This Session
        unit_show: true
        unit: kWh
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: sensor.32a_car_charging_last_session_step_1
          - entity_id: sensor.32a_car_charging_last_session_step_2
        text: Last Session
        unit_show: true
        unit: kWh
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: sensor.32a_car_charger_monthly_energy_step_1
          - entity_id: sensor.32a_car_charger_monthly_energy_step_2
        text: This Month
        unit_show: true
        unit: kWh
```
and the current card view:
![image](https://user-images.githubusercontent.com/49846893/199966547-881ab0cf-4eea-430f-96fe-8fe76bfe2873.png)

Monthly energy should be a sum of:
![image](https://user-images.githubusercontent.com/49846893/199966995-6333ae7a-34e6-478c-88ac-b3974fd279d6.png)
Those numbers are wrong though but that is beside the point!

**Comment by tmjo** [comment]
I'll look closer later, but I recall there has been some issues with the `statetext`-stuff. Your interpretation seems correct, but I think there are some issues with it on my side. See what happens if you delete the statetext-section. That may possibly make the stats appear independent of charging state (as default should do).

Not sure why the summation is not working though, I'll have to test myself. Meanwhile, could you try min/max/mean just to see if it works?

**Comment by danielbrunt57** [comment]
The stats section showed the individual step_2 session entity while the charger was on but it finished charging before I was able to finish editing the yaml for "sum".  I've removed `statetext` but no change...

**Comment by danielbrunt57** [comment]
min/max/mean do not change anything.
```
type: custom:charger-card
brand: other
entity: sensor.wallbox_32a_charger
customCardTheme: theme_custom
chargerImage: White
show_leds: true
show_collapsibles: false
details:
  name:
    entity_id: sensor.wallbox_32a_charger
    attribute: name
  location:
    entity_id: sensor.wallbox_32a_charger
    attribute: site_name
  status:
    entity_id: sensor.wallbox_32a_charger
  info_left:
    - entity_id: sensor.circuit_11_power
      text: power
      unit_show: true
  info_right:
    - entity_id: sensor.household_voltage
      text: voltage
      unit_show: true
  stats:
    default:
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: sensor.32a_car_charging_session_step_1
          - entity_id: sensor.32a_car_charging_session_step_2
        text: This Session
        unit_show: true
        unit: kWh
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: input_number.32a_car_charger_last_session_step_1
          - entity_id: input_number.32a_car_charger_last_session_step_1
        text: Last Session
        unit_show: true
        unit: kWh
      - entity_id: calculated
        calc_function: max
        calc_entities:
          - entity_id: sensor.32a_car_charger_monthly_energy_step_1
          - entity_id: sensor.32a_car_charger_monthly_energy_step_2
        text: This Month
        unit_show: true
        unit: kWh
```

**Comment by danielbrunt57** [comment]
`calculated` does not seem to work...
```
type: custom:charger-card
brand: other
entity: sensor.wallbox_32a_charger
customCardTheme: theme_custom
chargerImage: White
show_leds: true
show_collapsibles: false
details:
  name:
    entity_id: sensor.wallbox_32a_charger
    attribute: name
  location:
    entity_id: sensor.wallbox_32a_charger
    attribute: site_name
  status:
    entity_id: sensor.wallbox_32a_charger
  info_left:
    - entity_id: sensor.circuit_11_power
      text: power
      unit_show: true
  info_right:
    - entity_id: sensor.household_voltage
      text: voltage
      unit_show: true
  stats:
    default:
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: sensor.32a_car_charging_session_step_1
          - entity_id: sensor.32a_car_charging_session_step_2
        text: This Session
        unit_show: true
        unit: kWh
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: input_number.32a_car_charger_last_session_step_1
          - entity_id: input_number.32a_car_charger_last_session_step_1
        text: Last Session
        unit_show: true
        unit: kWh
      - entity_id: sensor.32a_car_charger_monthly_energy_step_1
        text: This Month
        unit_show: true
        unit: kWh
```
![image](https://user-images.githubusercontent.com/49846893/199974323-d6fbcf1f-6f02-434f-9af4-04082ca5a368.png)

**Comment by tmjo** [comment]
> `calculated` does not seem to work...
> 

Agreed, there is something fishy here. I'll try to figure out what is the problem.

**Comment by danielbrunt57** [comment]
I got the new version 0.1.2 just now. Thanks for fixing `calculated`!

**Comment by danielbrunt57** [comment]
My final card:
![image](https://user-images.githubusercontent.com/49846893/200206205-ab206f0d-1d14-433b-abab-af0d35d05c8d.png)
and code:
```
type: custom:charger-card
brand: other
entity: sensor.wallbox_32a_charger
customImage: /local/images/32A Wallbox (2).png
customCardTheme: theme_custom
chargerImage: White
show_leds: true
show_collapsibles: false
details:
  name:
    entity_id: sensor.wallbox_32a_charger
    attribute: name
  location:
    entity_id: sensor.wallbox_32a_charger
    attribute: site_name
  status:
    entity_id: sensor.wallbox_32a_charger
  statetext:
    'off': Idle
    'on': Charging
  info_left:
    - entity_id: sensor.circuit_11_power
      text: power
      unit_show: true
  info_right:
    - entity_id: sensor.household_voltage
      text: voltage
      unit_show: true
  stats:
    default:
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: sensor.32a_car_charging_session_step_1
          - entity_id: sensor.32a_car_charging_session_step_2
        text: This Session
        unit_show: true
        unit: kWh
        round: 1
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: input_number.32a_car_charger_last_session_step_1
          - entity_id: input_number.32a_car_charger_last_session_step_2
        text: Last Session
        unit_show: true
        unit: kWh
        round: 1
      - entity_id: calculated
        calc_function: sum
        calc_entities:
          - entity_id: sensor.32a_car_charger_monthly_energy_step_1
          - entity_id: sensor.32a_car_charger_monthly_energy_step_2
        text: This Month
        unit_show: true
        unit: kWh
        round: 1
      - entity_id: sensor.32a_car_charger_monthly_energy_step_1
        text: Step 1
        unit_show: true
        unit: kWh
        round: 1
      - entity_id: sensor.32a_car_charger_monthly_energy_step_2
        text: Step 2
        unit_show: true
        unit: kWh
        round: 1
card_mod:
  class: inline-card
```
