### ISSUE TITLE
Tesla custom integration configuration for charger-card

### ISSUE THREAD

**Issue by purcell-lab** [tmjo/charger-card#37]
The [Tesla Custom Integration](https://github.com/alandtse/tesla) v3 has gone through a bit of a rewrite, including some new naming schema for sensors. It now provides most of the necessary sensors to work with with the tmjo/charger-card and I have  documented my configuration here, to assist others and maybe have this included as a template.

Note this accesses vehicle data/ controls via the Tesla cloud API and not the Tesla high powered wall connector (HPWC) wallbox.

![image](https://user-images.githubusercontent.com/79175134/202274413-81556646-6d4b-4e13-95ba-43e8e825f3ed.png)

```yaml
type: custom:charger-card
entity: binary_sensor.duka_charger
customCardTheme: black
customImage: /local/tesla.png
details:
  name:
    entity_id: sensor.duka_vehicle_state_data
    attribute: vehicle_name
  location:
    entity_id: device_tracker.duka_location_tracker
  status:
    entity_id: binary_sensor.duka_charger
    attribute: charging_state
  substatus:
    entity_id: sensor.duka_charging
    attribute: charge_port_latch
  smartcharging:
    entity_id: binary_sensor.duka_charger
    attribute: fast_charger_type
  currentlimits:
    - 0
    - 1
    - 8
    - 16
  info_left:
    - entity_id: binary_sensor.duka_online
      attribute: state
  info_right:
    - entity_id: sensor.duka_battery
      icon: mdi:car-electric-outline
      unit: '%'
      unit_show: true
    - entity_id: sensor.duka_charger_power
      text: Power
      unit_show: true
      unit: kW
      icon: mdi:lightning-bolt
    - entity_id: sensor.duka_charger_power
      attribute: charger_volts
      text: voltage
      unit: V
      unit_show: true
      icon: mdi:sine-wave
    - entity_id: number.duka_charging_amps
      text: amp
      unit: A
      unit_show: true
      icon: mdi:current-ac
  stats:
    default:
      - entity_id: sensor.duka_charging_rate
        attribute: time_left
        text: remaining
        unit_show: true
        unit: hrs
      - entity_id: sensor.duka_energy_added
        text: Energy Added
        unit_show: true
        unit: kWh
      - entity_id: sensor.duka_charger_power
        attribute: charger_amps_request
        text: Request
        unit: A
        unit_show: true
      - entity_id: number.duka_charging_amps
        text: Actual
        unit: A
        unit_show: true
      - entity_id: switch.duka_charger
        text: Switch
  group2:
    - entity_id: sensor.duka_charging_rate
      attribute: charger_voltage
      text: voltage
      unit: V
      unit_show: true
    - entity_id: sensor.duka_charging_rate
      attribute: charger_amps_actual
      text: amp
      unit: A
      unit_show: true
    - entity_id: sensor.duka_charging_rate
      attribute: charger_power
      text: Power
      unit_show: true
      unit: kW
    - entity_id: sensor.duka_charging_rate
      attribute: charge_energy_added
      text: Energy Added
      unit_show: true
      unit: kWh
    - entity_id: sensor.duka_charging_rate
      attribute: charge_current_request
      text: Request
      unit: A
      unit_show: true
    - entity_id: sensor.duka_charging_rate
      attribute: charger_actual_current
      text: Actual
      unit: A
      unit_show: true
    - entity_id: switch.duka_charger
      text: Charger Switch
  toolbar_right:
    default:
      - service: script.tesla_charging_current_low
        text: Excess Solar Charging
        icon: mdi:solar-power
      - service: script.tesla_high
        text: 1A charging
        icon: mdi:numeric-1
      - service: script.tesla_16a
        text: 16A charging
        icon: mdi:numeric-9-plus
```

**Comment by tmjo** [comment]
Looks good. Is `duka` the name of your car, or is it something added by the integration?

**Comment by purcell-lab** [comment]
Yes, duka is the car name added by the Tesla Custom Integration.

**Comment by bobloadmire** [comment]
something is up with mine. I copy and pasted your code and updated the entities to my name, but it loooks like this:

![image](https://user-images.githubusercontent.com/4238740/215622931-28b3b976-a908-4b30-8b16-082b451e095c.png)

**Comment by purcell-lab** [comment]
> something is up with mine.

Maybe post your yaml and some of the sensor values

**Comment by bobloadmire** [comment]
`type: custom:charger-card
entity: binary_sensor.charger
customCardTheme: black
customImage: /local/tesla.png
details:
  name: Model Y
  location:
    entity_id: device_tracker.location_tracker
  status:
    entity_id: binary_sensor.charger
    attribute: charging_state
  substatus:
    entity_id: sensor.charging
    attribute: charge_port_latch
  smartcharging:
    entity_id: binary_sensor.charger
    attribute: fast_charger_type
  currentlimits:
    - 0
    - 1
    - 8
    - 16
  info_left:
    - entity_id: binary_sensor.online
      attribute: state
  info_right:
    - entity_id: sensor.battery
      icon: mdi:car-electric-outline
      unit: '%'
      unit_show: true
    - entity_id: sensor.charger_power
      text: Power
      unit_show: true
      unit: kW
      icon: mdi:lightning-bolt
    - entity_id: sensor.charger_power
      attribute: charger_volts
      text: voltage
      unit: V
      unit_show: true
      icon: mdi:sine-wave
    - entity_id: number.charging_amps
      text: amp
      unit: A
      unit_show: true
      icon: mdi:current-ac
  stats:
    default:
      - entity_id: sensor.charging_rate
        attribute: time_left
        text: remaining
        unit_show: true
        unit: hrs
      - entity_id: sensor.energy_added
        text: Energy Added
        unit_show: true
        unit: kWh
      - entity_id: sensor.charger_power
        attribute: charger_amps_request
        text: Request
        unit: A
        unit_show: true
      - entity_id: number.charging_amps
        text: Actual
        unit: A
        unit_show: true
      - entity_id: switch.charger
        text: Switch
  group2:
    - entity_id: sensor.charging_rate
      attribute: charger_voltage
      text: voltage
      unit: V
      unit_show: true
    - entity_id: sensor.charging_rate
      attribute: charger_amps_actual
      text: amp
      unit: A
      unit_show: true
    - entity_id: sensor.charging_rate
      attribute: charger_power
      text: Power
      unit_show: true
      unit: kW
    - entity_id: sensor.charging_rate
      attribute: charge_energy_added
      text: Energy Added
      unit_show: true
      unit: kWh
    - entity_id: sensor.charging_rate
      attribute: charge_current_request
      text: Request
      unit: A
      unit_show: true
    - entity_id: sensor.charging_rate
      attribute: charger_actual_current
      text: Actual
      unit: A
      unit_show: true
    - entity_id: switch.charger
      text: Charger Switch
  toolbar_right:
    default:
      - service: script.tesla_charging_current_low
        text: Excess Solar Charging
        icon: mdi:solar-power
      - service: script.tesla_high
        text: 1A charging
        icon: mdi:numeric-1
      - service: script.tesla_16a
        text: 16A charging
        icon: mdi:numeric-9-plus
`

**Comment by purcell-lab** [comment]
> ```yaml
> customImage: /local/tesla.png
> ```

Have you uploaded a custom image to the homeassistant/www folder, which is where you can see the car picture?  Alternativly remove the custom image line and you will get the default entry.

![image](https://user-images.githubusercontent.com/79175134/215643484-3ead8f7e-09aa-46b6-b310-8f62cb066519.png)

**Comment by bobloadmire** [comment]
ok fixed that, it decided to name it something else for some reason. now it looks like this:
![image](https://user-images.githubusercontent.com/4238740/215840904-a4388fcc-4bd8-4612-b348-a0f4654a02dc.png)

why is text overflowing the card?

**Comment by bobloadmire** [comment]
![image](https://user-images.githubusercontent.com/4238740/215907870-d35fa754-f08a-4c7a-af5f-e4e69fd590f0.png)


Nice looking good. Any way to update the text for "not_home" to Away or something? Or even better geolocation?

Do you have any more info on the service calls for charging? I have a 48a wall charger and the mobile charger too, so that would be handy.

**Comment by purcell-lab** [comment]
> why is text overflowing the card?

probably because you didn't have an updated image, which seems to be resolved in your latest update.

**Comment by purcell-lab** [comment]
> Any way to update the text for "not_home" to Away or something? Or even better geolocation?

That field is set by device_tracker.<carname>_location_tracker entity, you can change to a different field or even get the reverse geolocation, but will need to do some template work.
![image](https://user-images.githubusercontent.com/79175134/215910305-88eb454e-56e9-4e50-ab76-ea81340f1a95.png)

**Comment by purcell-lab** [comment]
> Whats the vertical grey bar, you have it on your image, as does mine.

Vertical grey bar is a legacy from the charging lights on the original wallbox graphics. @tmjo is there any way to remove the grey bar with a custom image?

**Comment by bobloadmire** [comment]
nice, thanks

**Comment by purcell-lab** [comment]
> Do you have any more info on the service calls for charging? I have a 48a wall charger and the mobile charger too, so that would be handy.

Yes, sorry the service calls at the bottom for the sun icon, 1 & 9+ icons are using the legacy interface and are just calling some scripts I have setup locally.  You can either use your own scripts, or here are the updated services for 1A & 16A amp charging.

```yaml
  toolbar_right:
    default:
      - service: script.tesla_charging_current_low
        text: Excess Solar Charging
        icon: mdi:solar-power
      - service: number.set_value
        service_data:
          entity_id: number.duka_charging_amps
          value: '1'
        text: 1A charging
        icon: mdi:numeric-1
      - service: number.set_value
        service_data:
          entity_id: number.duka_charging_amps
          value: '16'
        text: 16A charging
        icon: mdi:numeric-9-plus
```

**Comment by bobloadmire** [comment]
just curious, when would you use 1A and 16A charging? 1A is super slow, and 16A is more than a standard 120v outlet allows, but way lower than a Nema outlet, or a wall connector.  Think i'm going to do 12a, 24a and 48a

**Comment by bobloadmire** [comment]
ah cool. well If I ever get solar, i'll do that. would be cool if it was variable charging based on excess

**Comment by purcell-lab** [comment]
> would be cool if it was variable charging based on excess

Thats exactly what I do, the power of home assistant.  I dynamically calculate the excess solar and convert that to a 'charging_amps' entity which I update the car with every minute.

![image](https://user-images.githubusercontent.com/79175134/215914851-1cff8abc-e40c-46e1-bfc4-c030ccdc1948.png)


```yaml
    excess_solar_charging_amps:
      friendly_name_template: 'Excess Solar Charging Amps'
      value_template: >-
        {{ max(0,(states('sensor.apf_solar2grid')|int(0)+states('sensor.ev_power')|int(0)) 
          / states('sensor.ev_phases')|int(1) /
            max(220,states('sensor.ev_voltage')|int(230)))|int(0)}}
      unit_of_measurement: A
```

**Comment by bobloadmire** [comment]
nice work! you keep it just a hair below excess, nice code.

**Comment by purcell-lab** [comment]
Updated to [v0.2.0-alpha](https://github.com/tmjo/charger-card/tree/v0.2.0-alpha) and haven't noticed any changes to my Tesla configuration/ functionality.

![image](https://user-images.githubusercontent.com/79175134/220006609-ff01b6d9-cd2b-42b1-93e8-0fbc58481f19.png)

Thanks @tmjo for your great work.

**Comment by tmjo** [comment]
Sounds good! Would you mind checking if the UI-editor looks ok now?

Also, if you're feeling lucky, you may want to test the Tesla setup (from brands/template). Remember to backup your current YAML first so you can easily go back. Or even better, just setup a new additional card for experimenting. Perhaps we could edit the [Tesla template](https://github.com/tmjo/charger-card/blob/master/src/templates/const_tesla_custom.ts) to fit what you guys want/need?

**Comment by purcell-lab** [comment]
Visual editor is much improved and working as expected now.

![image](https://user-images.githubusercontent.com/79175134/220264881-60e48cc3-8ada-4ec7-8e26-7dbb6871ab11.png)

**Comment by purcell-lab** [comment]
Starting with an empty card, entity selection dialogue doesn't seem to make it easy to find what you want :-(

[Screen recording 2023-02-21 16.33.36.webm](https://user-images.githubusercontent.com/79175134/220266540-adda225f-bfa6-4e2e-99e3-a5e02889b43e.webm)

**Comment by purcell-lab** [comment]
After I manually entered the correct entity via code editor:

```yaml
type: custom:charger-card
entity: binary_sensor.duka_charger
```

selecting brand 'Tesla EV custom integration' presented a bunch of sensible defaults, and the card is usable.

![image](https://user-images.githubusercontent.com/79175134/220267595-e6ec9d68-5bf4-434b-9375-c21208a8eb96.png)

**Comment by purcell-lab** [comment]
Some minor amendments are needed (energy added button not functional) and my bespoke setup presents slightly different data.

![image](https://user-images.githubusercontent.com/79175134/220268429-2c369a59-692b-4556-a168-9511c0ec1272.png)
```yaml
type: custom:charger-card
entity: binary_sensor.duka_charger
customCardTheme: black
customImage: /local/tesla.png
show_leds: false
details:
  name:
    entity_id: sensor.duka_vehicle_state_data
    attribute: vehicle_name
  location:
    entity_id: device_tracker.duka_location_tracker
  status:
    entity_id: binary_sensor.duka_charger
    attribute: charging_state
  substatus:
    entity_id: sensor.duka_charging
    attribute: charge_port_latch
  smartcharging:
    entity_id: binary_sensor.duka_charger
    attribute: fast_charger_type
  currentlimits:
    - 0
    - 1
    - 8
    - 16
  info_left:
    - entity_id: binary_sensor.duka_online
      attribute: state
  info_right:
    - entity_id: sensor.duka_battery
      icon: mdi:car-electric-outline
      unit: '%'
      unit_show: true
    - entity_id: sensor.duka_charger_power
      text: Power
      unit_show: true
      unit: kW
      icon: mdi:lightning-bolt
    - entity_id: sensor.duka_charger_power
      attribute: charger_volts
      text: voltage
      unit: V
      unit_show: true
      icon: mdi:sine-wave
    - entity_id: number.duka_charging_amps
      text: amp
      unit: A
      unit_show: true
      icon: mdi:current-ac
  stats:
    default:
      - entity_id: sensor.duka_charging_rate
        attribute: time_left
        text: remaining
        unit_show: true
        unit: hrs
      - entity_id: sensor.duka_energy_added
        text: Energy Added
        unit_show: true
        unit: kWh
      - entity_id: sensor.duka_charger_power
        attribute: charger_amps_request
        text: Request
        unit: A
        unit_show: true
      - entity_id: number.duka_charging_amps
        text: Actual
        unit: A
        unit_show: true
      - entity_id: switch.duka_charger
        text: Switch
  group2:
    - entity_id: sensor.duka_charging_rate
      attribute: charger_voltage
      text: voltage
      unit: V
      unit_show: true
    - entity_id: sensor.duka_charging_rate
      attribute: charger_amps_actual
      text: amp
      unit: A
      unit_show: true
    - entity_id: sensor.duka_charging_rate
      attribute: charger_power
      text: Power
      unit_show: true
      unit: kW
    - entity_id: sensor.duka_charging_rate
      attribute: charge_energy_added
      text: Energy Added
      unit_show: true
      unit: kWh
    - entity_id: sensor.duka_charging_rate
      attribute: charge_current_request
      text: Request
      unit: A
      unit_show: true
    - entity_id: sensor.duka_charging_rate
      attribute: charger_actual_current
      text: Actual
      unit: A
      unit_show: true
    - entity_id: switch.duka_charger
      text: Charger Switch
  toolbar_right:
    default:
      - service: script.tesla_charging_current_low
        text: Excess Solar Charging
        icon: mdi:solar-power
      - service: number.set_value
        service_data:
          entity_id: number.duka_charging_amps
          value: '1'
        text: 1A charging
        icon: mdi:numeric-1
      - service: number.set_value
        service_data:
          entity_id: number.duka_charging_amps
          value: '16'
        text: 16A charging
        icon: mdi:numeric-9-plus
```
