### ISSUE TITLE
Toolbar not visible - style height on preview wrong

### ISSUE THREAD

**Issue by Enrica-r** [tmjo/charger-card#43]
I could not see the toolbar even if the setting was true. I have seen that the toolbar is rendered into the dom. With browsers development tool I found the toolbar hidden under the next following card. 

If i set height to auto in style class "preview", it works. I have seen that this setting is commented in style file already. Probably had some other issue with this.

Could you check the behaviour?

Regards, 
Enrica

**Comment by Enrica-r** [comment]
Hi,
It's in a vertical-stack. Attached you could see two screenshot with open devopment tool, one incorrect and one correct. I changed the height from 100% to auto in class preview.
Incorrect:
![Screenhot with error](https://user-images.githubusercontent.com/2463365/224550141-25d8e8aa-8784-45ff-83c2-0ebb578cbdb7.png)

Correct:

![Screenshot correct preview height auto](https://user-images.githubusercontent.com/2463365/224550175-4856b71d-affb-499b-a893-5463687709c9.png)

Here is the yaml code of the dashboard. It's long because I have to set the details. Only setting the brand and select my status entity and color does not work.

```yml
type: vertical-stack
cards:
  - type: markdown
    content: '# Ladeinfrastruktur Blattenstrasse 24'
  - square: false
    columns: 2
    type: grid
    cards:
      - type: custom:vertical-stack-in-card
        cards:
          - type: markdown
            content: '## Hausinfrastruktur'
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.strom_blattenstrasse_24_channel_a_current
                name: Phase 1
                unit: A
                min: 0
                max: 35
                severity:
                  green: 22
                  yellow: 25
                  red: 35
              - type: gauge
                entity: sensor.strom_blattenstrasse_24_channel_b_current
                name: Phase 2
                unit: A
                min: 0
                max: 35
                severity:
                  green: 22
                  yellow: 25
                  red: 35
              - type: gauge
                entity: sensor.strom_blattenstrasse_24_channel_c_current
                name: Phase 3
                unit: A
                min: 0
                max: 35
                severity:
                  green: 22
                  yellow: 25
                  red: 35
          - type: horizontal-stack
            cards:
              - show_name: true
                show_icon: true
                show_state: true
                type: glance
                entities:
                  - entity: sensor.strom_blattenstrasse_24_channel_a_power
                    name: Phase 1
                  - entity: sensor.strom_blattenstrasse_24_channel_b_power
                    name: Phase 2
                  - entity: sensor.strom_blattenstrasse_24_channel_c_power
                    name: Phase 3
                  - entity: sensor.strom_blattenstrasse24_total_power
                title: Energie
          - show_name: true
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: sensor.easee_phase_1_dyn_circuit_limit
              - entity: sensor.easee_phase_2_dyn_circuit_limit
              - entity: sensor.easee_phase_3_dyn_circuit_limit
            title: Ladelimite auf
      - type: vertical-stack
        cards:
          - type: markdown
            content: '## Ladeinfrastruktur'
          - type: custom:charger-card
            entity: sensor.parkplatz_26_27_status
            customCardTheme: null
            chargerImage: null
            brand: easee
            show_leds: true
            show_toolbar: true
            show_stats: true
            details:
              name:
                entity_id: sensor.parkplatz_26_27_status
                attribute: name
              location:
                entity_id: sensor.parkplatz_26_27_status
                attribute: site_name
              status:
                entity_id: sensor.parkplatz_26_27_status
              substatus:
                entity_id: sensor.parkplatz_26_27_reason_for_no_current
              smartcharging:
                entity_id: switch.parkplatz_26_27_smart_charging
              currentlimits:
                - 0
                - 6
                - 7
                - 8
                - 9
                - 10
                - 11
                - 12
                - 13
                - 14
                - 15
                - 16
              statetext:
                disconnected: disconnected
                awaiting_start: awaiting_start
                charging: charging
                completed: completed
                error: error
                ready_to_charge: ready_to_charge
              collapsiblebuttons:
                group1:
                  text: click_for_group1
                  icon: mdi:speedometer
                group2:
                  text: click_for_group2
                  icon: mdi:information
                group3:
                  text: click_for_group3
                  icon: mdi:cog
              info_left:
                - entity_id: binary_sensor.parkplatz_26_27_online
                  text: online
              info_right:
                - entity_id: sensor.parkplatz_26_27_voltage
                  text: voltage
                  unit_show: true
                - entity_id: sensor.parkplatz_26_27_power
                  text: power
                  unit_show: true
              group1:
                - entity_id: sensor.parkplatz_26_27_dynamic_charger_limit
                  text: dyn_charger_limit
                  service: easee.set_charger_dynamic_limit
                  service_data:
                    charger_id: ECKHG8D4
                    current: '#SERVICEVAL#'
                - entity_id: sensor.parkplatz_26_27_dynamic_circuit_limit
                  text: dyn_circuit_limit
                  service: easee.set_charger_circuit_dynamic_limit
                  service_data:
                    charger_id: ECKHG8D4
                    currentP1: '#SERVICEVAL#'
                - entity_id: sensor.parkplatz_26_27_max_charger_limit
                  text: max_charger_limit
                  service: easee.set_charger_max_limit
                  service_data:
                    charger_id: ECKHG8D4
                    current: '#SERVICEVAL#'
                - entity_id: sensor.parkplatz_26_27_max_circuit_limit
                  text: max_circuit_limit
                  service: easee.set_circuit_max_limit
                  service_data:
                    charger_id: ECKHG8D4
                    currentP1: '#SERVICEVAL#'
                - entity_id: sensor.parkplatz_26_27_offline_circuit_limit
                  text: offline_circuit_limit
                  service: easee.set_charger_circuit_offline_limit
                  service_data:
                    charger_id: ECKHG8D4
                    currentP1: '#SERVICEVAL#'
              group2:
                - entity_id: binary_sensor.parkplatz_26_27_online
                  text: online
                - entity_id: sensor.parkplatz_26_27_voltage
                  text: voltage
                  unit_show: true
                - entity_id: sensor.parkplatz_26_27_power
                  text: power
                  unit_show: true
                - entity_id: sensor.parkplatz_26_27_current
                  text: charger_current
                  unit_show: true
                - entity_id: sensor.parkplatz_26_27_circuit_current
                  text: circuit_current
                  unit_show: true
                - entity_id: sensor.parkplatz_26_27_energy_per_hour
                  text: energy_per_hour
                  unit_show: true
                - entity_id: sensor.parkplatz_26_27_session_energy
                  text: session_energy
                  unit_show: true
                - entity_id: sensor.parkplatz_26_27_lifetime_energy
                  text: lifetime_energy
                  unit_show: true
              group3:
                - entity_id: switch.parkplatz_26_27_is_enabled
                  text: enabled
                - entity_id: switch.parkplatz_26_27_enable_idle_current
                  text: idle_current
                - entity_id: binary_sensor.parkplatz_26_27_cable_locked
                  text: cable_locked
                - entity_id: switch.parkplatz_26_27_cable_locked_permanently
                  text: perm_cable_locked
                - entity_id: switch.parkplatz_26_27_smart_charging
                  text: smart_charging
                - entity_id: sensor.parkplatz_26_27_cost_per_kwh
                  text: cost_per_kwh
                - entity_id: binary_sensor.parkplatz_26_27_update_available
                  text: update_available
                - entity_id: binary_sensor.parkplatz_26_27_basic_schedule
                  text: schedule
              stats:
                default:
                  - entity_id: sensor.parkplatz_26_27_session_energy
                    text: session_energy
                    unit_show: true
                  - entity_id: switch.parkplatz_26_27_cable_locked_permanently
                    text: cable_locked
                  - entity_id: binary_sensor.parkplatz_26_27_basic_schedule
                    text: schedule
                disconnected:
                  - entity_id: sensor.parkplatz_26_27_session_energy
                    text: session_energy
                    unit_show: true
                  - entity_id: switch.parkplatz_26_27_cable_locked_permanently
                    text: cable_locked
                  - entity_id: calculated
                    text: used_limit
                    unit: A
                    unit_show: true
                    calc_function: min
                    calc_entities:
                      - entity_id: sensor.parkplatz_26_27_dynamic_charger_limit
                      - entity_id: sensor.parkplatz_26_27_dynamic_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_max_charger_limit
                      - entity_id: sensor.parkplatz_26_27_max_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_offline_circuit_limit
                awaiting_start:
                  - entity_id: sensor.parkplatz_26_27_session_energy
                    text: session_energy
                    unit_show: true
                  - entity_id: binary_sensor.parkplatz_26_27_basic_schedule
                    text: schedule
                  - entity_id: switch.parkplatz_26_27_smart_charging
                    text: smart_charging
                  - entity_id: calculated
                    text: used_limit
                    unit: A
                    unit_show: true
                    calc_function: min
                    calc_entities:
                      - entity_id: sensor.parkplatz_26_27_dynamic_charger_limit
                      - entity_id: sensor.parkplatz_26_27_dynamic_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_max_charger_limit
                      - entity_id: sensor.parkplatz_26_27_max_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_offline_circuit_limit
                charging:
                  - entity_id: sensor.parkplatz_26_27_session_energy
                    text: session_energy
                    unit_show: true
                  - entity_id: sensor.parkplatz_26_27_energy_per_hour
                    text: energy_per_hour
                    unit_show: true
                  - entity_id: sensor.parkplatz_26_27_circuit_current
                    text: circuit_current
                    unit_show: true
                  - entity_id: sensor.parkplatz_26_27_output_limit
                    text: output_limit
                    unit_show: true
                  - entity_id: sensor.parkplatz_26_27_current
                    text: current
                    unit_show: true
                  - entity_id: sensor.parkplatz_26_27_power
                    text: power
                    unit_show: true
                completed:
                  - entity_id: sensor.parkplatz_26_27_session_energy
                    text: session_energy
                    unit_show: true
                  - entity_id: binary_sensor.parkplatz_26_27_basic_schedule
                    text: schedule
                  - entity_id: calculated
                    text: used_limit
                    unit: A
                    unit_show: true
                    calc_function: min
                    calc_entities:
                      - entity_id: sensor.parkplatz_26_27_dynamic_charger_limit
                      - entity_id: sensor.parkplatz_26_27_dynamic_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_max_charger_limit
                      - entity_id: sensor.parkplatz_26_27_max_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_offline_circuit_limit
                error:
                  - entity_id: sensor.parkplatz_26_27_session_energy
                    text: session_energy
                    unit_show: true
                  - entity_id: binary_sensor.parkplatz_26_27_basic_schedule
                    text: schedule
                ready_to_charge:
                  - entity_id: sensor.parkplatz_26_27_session_energy
                    text: session_energy
                    unit_show: true
                  - entity_id: binary_sensor.parkplatz_26_27_basic_schedule
                    text: schedule
                  - entity_id: calculated
                    text: used_limit
                    unit: A
                    unit_show: true
                    calc_function: min
                    calc_entities:
                      - entity_id: sensor.parkplatz_26_27_dynamic_charger_limit
                      - entity_id: sensor.parkplatz_26_27_dynamic_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_max_charger_limit
                      - entity_id: sensor.parkplatz_26_27_max_circuit_limit
                      - entity_id: sensor.parkplatz_26_27_offline_circuit_limit
              toolbar_left:
                default:
                  - {}
                disconnected:
                  - {}
                awaiting_start:
                  - service: easee.stop
                    service_data:
                      charger_id: ECKHG8D4
                    text: stop
                    icon: hass:stop
                  - service: easee.resume
                    service_data:
                      charger_id: ECKHG8D4
                    text: resume
                    icon: hass:play
                  - service: easee.override_schedule
                    service_data:
                      charger_id: ECKHG8D4
                    text: override
                    icon: hass:motion-play
                charging:
                  - service: easee.stop
                    service_data:
                      charger_id: ECKHG8D4
                    text: stop
                    icon: hass:stop
                  - service: easee.pause
                    service_data:
                      charger_id: ECKHG8D4
                    text: pause
                    icon: hass:pause
                completed:
                  - service: easee.stop
                    service_data:
                      charger_id: ECKHG8D4
                    text: stop
                    icon: hass:stop
                  - service: easee.override_schedule
                    service_data:
                      charger_id: ECKHG8D4
                    text: override
                    icon: hass:motion-play
                error:
                  - service: easee.reboot
                    service_data:
                      charger_id: ECKHG8D4
                    text: reboot
                    icon: hass:restart
                ready_to_charge:
                  - service: easee.stop
                    service_data:
                      charger_id: ECKHG8D4
                    text: stop
                    icon: hass:stop
                  - service: easee.override_schedule
                    service_data:
                      charger_id: ECKHG8D4
                    text: override
                    icon: hass:motion-play
              toolbar_right:
                default:
                  - service: persistent_notification.create
                    service_data:
                      message: >-
                        Firmware update is available, but only possible when
                        disconnected!
                      title: Update
                    text: update
                    icon: mdi:file-download
                    conditional_entity: binary_sensor.parkplatz_26_27_update_available
                disconnected:
                  - service: easee.update_firmware
                    service_data:
                      charger_id: ECKHG8D4
                    text: update
                    icon: mdi:file-download
                    conditional_entity: binary_sensor.parkplatz_26_27_update_available
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.easee_phase_1_current
                name: Phase 1
                min: 0
                max: 16
                needle: true
              - type: gauge
                entity: sensor.easee_phase_2_current
                name: Phase 2
                min: 0
                max: 16
                needle: true
              - type: gauge
                entity: sensor.easee_phase_3_current
                name: Phase 3
                min: 0
                max: 16
                needle: true
  - type: markdown
    content: '## Mein Auto Tesla Model Y'
  - square: true
    columns: 3
    type: grid
    cards:
      - type: custom:vertical-stack-in-card
        cards:
          - type: markdown
            content: '### Informationen'
          - type: entities
            entities:
              - entity: sensor.tessie_battery
              - entity: sensor.tessie_range
              - entity: binary_sensor.tessie_asleep
              - entity: update.tessie_software_update
              - entity: lock.tessie_doors
              - entity: sensor.tessie_temperature_inside
              - entity: sensor.tessie_temperature_outside
            state_color: true
      - type: custom:vertical-stack-in-card
        cards:
          - type: markdown
            content: Einstellungen tätigen
          - type: entities
            entities:
              - entity: button.tessie_wake_up
              - entity: cover.tessie_windows
              - entity: switch.tessie_sentry_mode
              - entity: number.tessie_charge_limit
              - entity: number.tessie_charging_amps
              - entity: switch.tessie_charger
            state_color: true
      - type: custom:vertical-stack-in-card
        cards:
          - type: markdown
            content: '### Ladedaten'
          - type: entities
            entities:
              - entity: binary_sensor.tessie_charger
              - entity: binary_sensor.tessie_charging
              - entity: sensor.tessie_charger_power
              - entity: sensor.tessie_charging_rate
              - entity: sensor.tessie_time_charge_complete
              - entity: binary_sensor.tessie_scheduled_charging
              - entity: binary_sensor.tessie_scheduled_departure
              - entity: sensor.tessie_energy_added
            state_color: true
```
