### ISSUE TITLE
Show basic schedule times

### ISSUE THREAD

**Issue by corvy** [tmjo/charger-card#49]
Is there a way to show the basic schedule on the card? I use this actively with powersaver.no to create a basic schedule and it would increase the WAF alot if I could show the start/end time on the card. Is that possible?

**Comment by tmjo** [comment]
Hi! It is quite easy to make it show by displaying the schedule_chargeStartTime and schedule_chargeStopTime attributes of the basic schedule entity. However, I am not sure if the WAF is acceptable though since it by default displays full blown dateformat. 

Example:
```
  stats:
    disconnected:
      - entity_id: binary_sensor.easee_1_basic_schedule
        text: Start time
        attribute: schedule_chargeStartTime
```

![image](https://user-images.githubusercontent.com/54450177/234781187-dfc8aa96-4adb-4867-80fa-cd70765b261d.png)

You could add it to the stats below the card like example above or you could do it in one of the expanding menus in a similar way. In my example I added it to disconnected status just for testing, make sure you add it to the states where you want it shown.

I'll see if I can find an easy way to add some formatting in a future release, sounds like a good idea. In the meantime and as a workaround, it should be possible to use [HA template entities](https://www.home-assistant.io/integrations/template/) and extract the attributes into separate sensor and at the same time format it to the format of your liking. There is an example of time formatting in the link.

**Comment by corvy** [comment]
Great suggestion! 

I made this template in HA:


```
template:
  - sensor:
      - name: "Eneren Start Tid"
        state: >
          {{ as_timestamp(state_attr('binary_sensor.eneren_basic_schedule', 'schedule_chargeStartTime')) | timestamp_custom("%H:%M") }}
      - name: "Eneren Ferdig Tid"
        state: >
          {{ as_timestamp(state_attr('binary_sensor.eneren_basic_schedule', 'schedule_chargeStopTime')) | timestamp_custom("%H:%M") }}
      - name: "Toeren Start Tid"
        state: >
          {{ as_timestamp(state_attr('binary_sensor.toeren_basic_schedule', 'schedule_chargeStartTime')) | timestamp_custom("%H:%M") }}
      - name: "Toeren Ferdig Tid"
        state: >
          {{ as_timestamp(state_attr('binary_sensor.toeren_basic_schedule', 'schedule_chargeStopTime')) | timestamp_custom("%H:%M") }}

```

And now I could add these to my charge cards. 

![Screenshot_20230427_195201_Home Assistant](https://user-images.githubusercontent.com/138292/234950898-e372362e-a07f-4ae3-b520-4ff0e53d16a8.jpg)

```
  stats:
    default:
      - entity_id: sensor.eneren_session_energy
        text: Siste lading
        unit_show: true
      - entity_id: sensor.eneren_start_tid
        text: Ladestart
      - entity_id: sensor.eneren_ferdig_tid
        text: Ferdigladet
      - entity_id: switch.eneren_cable_locked_permanently
        text: Kabellås
        unit_show: false
```
Thanks a million!
