### ISSUE TITLE
go-e Charger

### ISSUE THREAD

**Issue by tomik671108** [tmjo/charger-card#57]
Good morning.
I really like the created card.
I would like to adapt the card to my go-e Charger myself, but I don't know if I can do it, I'm not that advanced yet.
Is it possible to include the go-e Charger in the list of devices?.
Documentation needed:
[https://github.com/goecharger/go-eCharger-API-v2](url)
[https://github.com/syssi/homeassistant-goecharger-mqtt](url)
The behavior of the LEDs is described in the user manual:
[https://strapi-s3-bucket.s3.eu-central-1.amazonaws.com/20230613_go_e_Charger_Gemini_FLEX_INSTALLATION_AND_OPERATING_GUIDE_EN_WEB_V1_2_832adb73fc.pdf](url)
Regards
tomik67

**Comment by tmjo** [comment]
Hi!

Thanks for your kind words. I'd love to add support for your charger, but kindly read the [wiki on how-to first](https://github.com/tmjo/charger-card/wiki/How-to-add-template-for-new-brand). Let me know if anything is unclear. 

Cheers!

**Comment by tmjo** [comment]
Hi,

Sounds nice you are having progress! 

Unfortunately the select-entity is not fully supported "natively" as it wasn't available when the card was initially made. It seems quite popular these days, so I'll take a look at implementing it better (but don't expect it to happen very soon though, days are too full right now). 

You probably already know, but a basic implementation works, for instance something like:
```
  group2:
    - entity_id: select.go_echarger_212417_ust
      text: Your custom text if you want one
```
The above will open the HA default UI when clicking on the select entity of the card, so it's not using the card dropdown items and gives an additional step which is of course not the intetion of the card. If there was a service to call, the card has an option to use custom dropdownitems. The current limit list is used as default, so you would have to specify to use those dropdowns like the below example:
```
  group2:
    - entity_id: select.go_echarger_212417_ust
      text: Your text if you want one
      type: dropdown
      dropdownitems:
        - Normal
        - Auto Unlock
        - Always Locked
```
Yet, the card does nothing with the selection. You'd have to specify a service call for that to happen which works well for "regular" services. I see that the select integration provides a service call named [select.select_option](https://www.home-assistant.io/integrations/select/) which in theory may work with the card. Something like:
```
  group2:
    - entity_id: select.go_echarger_212417_ust
      text: Your text if you want one
      type: dropdown
      dropdownitems:
        - Normal
        - Auto Unlock
        - Always Locked
      service: select.select_option
      service_data:
        target:
          entity_id: select.go_echarger_212417_ust
        data:
          option: '#SERVICEVAL#'
```
I'm not sure if the select integration requires the value (for instance 0)  or if it allows for the text (for instance "Normal") to be sent. Something like the below should in theory work, but I couldn't get it running when doing a quick test on one of my select-entities:
```
  group2:
    - entity_id: select.pump1
      text: Pump1
      type: dropdown
      dropdownitems:
        - 'Off'
        - Medium
        - High
      service: select.select_option
      service_data:
        target:
          - entity_id: select.pump1
        data:
          - option: '#SERVICEVAL#'
```
The value #SERVICEVAL is replaced by the card to selected value when executing the call. Either I did some silly mistakes in my test here, or there is some kind of bug or mismatch with the select service call. Perhaps you could fool around with it and see if you get it working or what error messages you get?

**Comment by tomik671108** [comment]
I tried this:
    - entity_id: select.go_echarger_212417_lmo
      text: Logic_mode
      type: dropdown
      dropdownitems:
        - Default
        - Eco mode
        - Automatic Stop
      service: select.select_option
      service_data:
        target:
          entity_id: select.go_echarger_212417_lmo
        data:
          option: '#SERVICEVAL#'

....and I get the following message:
Failed to call select/select_option service. extra keys not allowed @ data['data']

When I call it directly from the entity, I get the following message:
The state has changed to "Eco mode" triggered by the select.select_option service

**Comment by tmjo** [comment]
Yeah, that's what I got. There might be some incompatability. I'll see if I can fix it.

**Comment by tomik671108** [comment]
It would be great

**Comment by tomik671108** [comment]
I think I managed to get this function to work properly, now it looks like this and works:

`    - entity_id: select.go_echarger_212417_lmo
      text: Logic mode
      icon: mdi:format-list-checkbox
      type: dropdown
      dropdownitems:
        - Default
        - Eco mode
        - Automatic Stop
      service: select.select_option
      service_data:
        option: '#SERVICEVAL#'
        entity_id: select.go_echarger_212417_lmo`

....and the forum post on this topic was helpful.:
[https://smarthome.community/topic/1008/home-assistant-service-call-json-formatting-question/8](url)
....where it says:
"Yeaup I have run into this issue with as well, for some reason HA doesn't like it.target"

**Comment by tomik671108** [comment]
I'm sorry that the code looks like this, before when I pasted the formatting was correct, in the preview I have it normally.

**Comment by IamMattM** [comment]
I have just stumbled across this post.
Recently acquired a go-e gemini and will be interested to read through the progress made here.

**Comment by K3vb3rt** [comment]
I just installed the Gemini as well. Is anyone so kind and shares his code for a nice Gemini card (template)? Im not able to configure :-(

**Comment by IamMattM** [comment]
> I just installed the Gemini as well. Is anyone so kind and shares his code for a nice Gemini card (template)? Im not able to configure :-(

I have not had the opportunity to look into it myself since, but I gather that @tomik671108 might already have sussed out the required `yaml` for the card and a new `const_goe.ts` supporting the Go-e gemini (using go-e mqtt integration) ?

If so it would be great to have visibility of this if working for you @tomik671108  ?

**Comment by tomik671108** [comment]
My card looks like this:

<img width="441" alt="Zrzut ekranu 2024-04-11 o 20 23 26" src="https://github.com/tmjo/charger-card/assets/133171183/4a5fd317-73c3-407b-9b97-17eb04760406">

At the top, on the left side, I have placed additional information that you can remove if you do not need it, from the top they are:

- charger WiFi signal strength (RSSI)
- pGrid value, i.e. the value of exporting electricity from solar panels to the power grid (the vehicle is charged with surplus energy)
- expected maximum charging value
- information about the vehicle's battery status
- current, predicted range of the vehicle

Here is the configuration page:

<img width="1003" alt="Zrzut ekranu 2024-04-11 o 20 24 27" src="https://github.com/tmjo/charger-card/assets/133171183/47b13e24-487a-4a9c-9a02-5a59f4bc97ec">

Photos of the charger to choose from:

![go-e-charger-gemini-22-kw_frontansicht](https://github.com/tmjo/charger-card/assets/133171183/ac0647d7-9318-4ad2-af3d-f31404e36399)

![go-e-charger-gemini-22-kw-laden-frontansicht](https://github.com/tmjo/charger-card/assets/133171183/a60ce932-09b9-4700-9722-72e343c1b24d)

You need to put them in the Home Assistant folder, for example:
config//local/assets/go-e-charger-gemini-22-kw_frontansicht.png

And now the code that works for me, fill out the configuration page, confirm, go to "show code editor" and paste the code, but replace the entities with your own, the code is in the attachment because it formats incorrectly.:

[go-e_card.txt](https://github.com/tmjo/charger-card/files/14950320/go-e_card.txt)

**Comment by K3vb3rt** [comment]
Thank you soooo much!! Much appreciate it :-) Made my day <3

**Comment by IamMattM** [comment]
@tomik671108 
You're a STAR ! This card looks great !
Thank you for taking the time to post back all of this information, and share the outcome of your effort in porting the card for the go-e EVSE.
Looks very neat indeed.

**Comment by IamMattM** [comment]
@tmjo @tomik671108 
Got your version of the custom card for my go-e EVSE working as per your clear instructions (needed HACS custom brand icon package for the hyundai logo) 

![image](https://github.com/tmjo/charger-card/assets/29542928/c960a6ac-b25d-4193-8a17-3b874579a211)

I was wondering if you had or already knew of a way to use an animated .gif overlay that would be triggered when the charger is active ?
What name should it take ?

![go-e-ChargingOverlay,gif](https://github.com/tmjo/charger-card/assets/29542928/5e0c133a-3126-4fb0-b8d3-f71c6d59b7ad)

**Comment by IamMattM** [comment]
![go-e-ChargingOverlay](https://github.com/tmjo/charger-card/assets/29542928/7f6fb14a-544c-4bad-9490-e29f34b693b2)

**Comment by zeratax** [comment]
@tomik671108 that looks really amazing but ends up kinda weird for me? instead of the proper state names for selects I get the internal values or something?

<img width="491" height="556" alt="Image" src="https://github.com/user-attachments/assets/976ee01a-620e-4f14-b14b-257b5f854c9c" />

like instead of eco mode it says 4 here, which is what the value internally is according to the dev tools

<img width="1103" height="773" alt="Image" src="https://github.com/user-attachments/assets/57bd953b-987b-46ff-8800-f12b8c92cc3b" />
but when I otherwise select the entity I get the proper states:

<img width="600" height="460" alt="Image" src="https://github.com/user-attachments/assets/b1e00a88-1ad6-4993-a51d-6ef80d97ef2a" />

<details>
<summary>Here my config:</summary>


```yaml
type: custom:charger-card
customImage: /local/assets/go-e-charger-gemini-22-kw_frontansicht.png
entity: sensor.goe_408584_modelstatus_value
compact_view: false
show_name: true
show_status: true
show_leds: false
show_collapsibles: true
show_stats: true
show_toolbar: true
details:
  name:
    entity_id: sensor.goe_408584_modelstatus_value
    attribute: name
  location:
    entity_id: null
    attribute: null
  status:
    entity_id: sensor.goe_408584_car_value
  substatus:
    entity_id: sensor.goe_408584_loa
  smartcharging:
    entity_id: number.goe_408584_amp
  currentlimits1:
    - 0
    - 6
    - 10
    - 16
    - 20
    - 25
    - 32
  statetext:
    disconnected: Nicht verbunden
    awaiting_start: Warten auf Start
    charging: Lädt
    completed: Abgeschlossen
    error: Fehler
    ready_to_charge: Bereit zum Laden
  collapsiblebuttons:
    group1:
      text: Klicken für Gruppe 1
      icon: mdi:speedometer
    group2:
      text: Klicken für Gruppe 2
      icon: mdi:information
    group3:
      text: Klicken für Gruppe 3
      icon: mdi:cog
  info_left:
    - entity_id: sensor.goe_408584_rssi
      text: Online
      icon: mdi:wifi
    - entity_id: sensor.goe_408584_pgrid
      text: Netzleistung
      icon: phu:charging-station
    - entity_id: sensor.goe_408584_acu
      text: Maximal erlaubter Strom
      unit_show: true
      icon: mdi:current-ac
    - entity_id: sensor.xxxxxx_state_of_charge
      text: Batteriestand
      unit_show: true
      icon: phu:mercedes
    - entity_id: sensor.xxxxxx_range_electric
      text: Reichweite
      unit_show: true
      icon: phu:mercedes
  info_right:
    - entity_id: sensor.goe_408584_nrg_0
      text: Spannung
      unit_show: true
    - entity_id: sensor.goe_408584_nrg_12
      text: Leistung
      unit_show: true
    - entity_id: binary_sensor.goe_408584_car_0
      statetext:
        "off": Inaktiv
        "on": Lädt
      unit_show: false
  group1:
    - entity_id: select.goe_408584_lmo
      text: Logikmodus
      icon: mdi:format-list-checkbox
      type: dropdown
      dropdownitems:
        - Standard
        - Öko-Modus
        - Automatischer Stopp
      service: select.select_option
      service_data:
        option: "#SERVICEVAL#"
        entity_id: select.goe_408584_lmo
    - entity_id: select.goe_408584_frc
      text: Ladezustand erzwingen
      icon: mdi:auto-fix
      type: dropdown
      dropdownitems:
        - Neutral
        - Nicht laden
        - Laden
      service: select.select_option
      service_data:
        option: "#SERVICEVAL#"
        entity_id: select.goe_408584_frc
    - entity_id: select.goe_408584_ust
      text: Kabel-Entsperrmodus
      icon: mdi:account-lock-open
      type: dropdown
      dropdownitems:
        - Normal
        - Automatisch entsperren
        - Immer gesperrt
      service: select.select_option
      service_data:
        option: "#SERVICEVAL#"
        entity_id: select.goe_408584_ust
    - entity_id: select.goe_408584_psm
      text: Phasenumschaltmodus
      icon: mdi:speedometer
      type: dropdown
      dropdownitems:
        - Automatisch
        - Einphasig erzwingen
        - Dreiphasig erzwingen
      service: select.select_option
      service_data:
        option: "#SERVICEVAL#"
        entity_id: select.goe_408584_psm
  group2:
    - entity_id: sensor.goe_408584_nrg_5
      text: Stromstärke L1
      unit_show: true
    - entity_id: sensor.goe_408584_nrg_6
      text: Stromstärke L2
      unit_show: true
    - entity_id: sensor.goe_408584_nrg_7
      text: Stromstärke L3
      unit_show: true
    - entity_id: sensor.goe_408584_wh
      text: Energie pro Stunde
      unit_show: true
    - entity_id: sensor.goe_408584_eto
      text: Gesamtenergie
      unit_show: true
    - entity_id: sensor.goe_408584_tpa
      text: Durchschnittliche Gesamtleistung
      unit_show: true
  group3:
    - entity_id: number.goe_408584_ama
      icon: mdi:current-ac
      text: Maximale Strombegrenzung
      unit_show: true
      service: set.goe_408584_ama
    - entity_id: number.goe_408584_amp
      icon: mdi:current-ac
      text: Angeforderte Stromstärke
      unit_show: true
      service: set.goe_408584_amp
    - entity_id: switch.goe_408584_fup
      icon: mdi:solar-power
      text: PV-Überschuss nutzen
    - entity_id: switch.goe_408584_ara
      icon: phu:sleepiq
      text: Automatischer Stoppmodus
    - entity_id: number.goe_408584_ate
      icon: mdi:flash-auto
      text: Automatische Stoppenergie
    - entity_id: number.goe_408584_att
      icon: mdi:av-timer
      text: Automatische Stoppzeit
customCardTheme: theme_default
```

<summary>
