### ISSUE TITLE
Include documentation for attributes used

### ISSUE THREAD

**Issue by pcon** [tmjo/charger-card#6]
I'm trying to use this card for my [wallbox](https://github.com/hesselonline/wallbox) charger, but all of the sensors are separated instead of being a single one with lots of attributes.  Can you provide an example of the sensor and it's attributes that you are using for this?  That way I can create a template sensor that pulls in all of the other sensors into attributes.

**Comment by tmjo** [comment]
Hi @pcon! Yes, you're right. The card is written specifically for the [Easee charger](https://github.com/fondberg/easee_hass). It was my intention to extend it to support other brands, but it may be a bit complex since there is no "base class" for chargers to inherit from so all different chargers will work in different ways in HA. Anyway, I believe you're idea of using template sensors may work (or at least partly), so it could be worth a shot. If it seems to work well for the Wallbox, I may consider to try to add some more official support.

Take a look in the [const](https://github.com/fondberg/easee_hass/blob/master/custom_components/easee/const.py)-file for Easee, look for the two dicts MANDATORY_EASEE_ENTITIES and OPTIONAL_EASEE_ENTITIES and the entity names used by Easee. For instance the first one «status» appears in HA as «sensor.CHARGERNAME_status» and this is the main sensor the card expects and then (dirty, I know) uses this main sensor name to predict the other ones.

Mind sharing how it looks for the Wallbox entity/entities?

**Comment by pcon** [comment]
Here's a screenshot of the entries I have

![Wallbox Screenshot](https://user-images.githubusercontent.com/522876/120494455-d667e100-c389-11eb-9bff-2cfc5dd4e0f2.png)

So it sounds like the Easee charger does a bunch of entities as well.  It would be nice to have the component read everything from under a single sensor so you could do

```yaml
- platform: template
  sensors:
    garage_charger:
      friendly_name: "Garage EV Charger"
      value_template: '{{ states("sensor.wallbox_portal_status_description") }}'
      attribute_templates:
        siteName: 'Home'
        maxChargerCurrent: '{{ states("number.wallbox_portal_max_charging_current") }}'
        sessionEnergy: '{{ states("sensor.wallbox_portal_added_energy") }}'
```

And then in the card just reference `garage_charger.attributes.siteName`
