### ISSUE TITLE
Allow custom stuff in the groups.

### ISSUE THREAD

**Issue by blair287** [tmjo/charger-card#74]
Is it not possible to allow groups which just expand and show default entities of home assistant so for example can make a group which shows intelligent octopus info like switch for bump charge, time options etc currently if i try this it displays stuff but if i click on any items it always brings up current limits.

**Comment by naked-head** [comment]
You need to set it to _type_: service, dropdown, or info.
Here’s mine, and it works like a charm:

````
group1:
    - entity_id: number.1p7k_limite_dinamico
      text: Limite Dinamico
      unit_show: true
      icon: mdi:ray-vertex
      type: dropdown
      dropdownitems:
        - 6
        - 10
        - 13
        - 16
        - 20
        - 25
        - 32
      service: number.set_value
      service_data:
        entity_id: number.1p7k_limite_dinamico
        value: "#SERVICEVAL#"
    - entity_id: number.1p7k_led_brightness
      text: Luminosità LED
      icon: mdi:ray-vertex
      unit_show: true
      type: dropdown
      dropdownitems:
        - 25
        - 50
        - 75
        - 100
      service: number.set_value
      service_data:
        entity_id: number.1p7k_led_brightness
        value: "#SERVICEVAL#"
    - entity_id: switch.1p7k_autenticazione
      text: Autenticazione
      icon: mdi:fingerprint
      type: service
      service: switch.toggle
      service_data:
        entity_id: switch.1p7k_autenticazione
    - entity_id: switch.1p7k_blocca
      text: Bloccato
      icon: mdi:lock-outline
      type: service
      service: switch.toggle
      service_data:
        entity_id: switch.1p7k_blocca
````
